AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the prometheus helm chart into an existing kubernetes cluster (qs-1qde66ffn)"
Parameters:
  HelmLambdaArn:
    Type: String
  KubeConfigPath:
    Type: String
  KubeConfigKmsContext:
    Type: String
    Default: "EKSQuickStart"
Resources:
  # Install prometheus helm chart
  PrometheusHelmChart:
    Type: "Custom::Helm"
    Version: "1.0"
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Namespace: prometheus
      Chart: stable/prometheus
      Name: prometheus
      Values:
        server.persistentVolume.storageClass: "gp2"
        server.statefulSet.enabled: true
        server.replicaCount: 2
        server.service.sessionAffinity: ClientIP
        alertmanager.persistentVolume.storageClass: "gp2"
        alertmanager.statefulSet.enabled: true
        alertmanager.replicaCount: 2
Outputs:
  PrometheusReleaseName:
    Value: !Ref PrometheusHelmChart
